name: CICD-PULL-REQUEST

on:
  pull_request:

jobs:
  build-and-unit-test:
    name: build-and-unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Consensus library checkout code
        uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y cmake \
                              libssl-dev \
                              libgflags-dev \
                              libsnappy-dev
          sudo ln -s /usr/bin/cmake /usr/bin/cmake3
          sudo ln -s /usr/bin/ctest /usr/bin/ctest3
      - name: make
        run: |
          mkdir bu
          cd bu
          cmake3 -B ./ -D WITH_DEBUG=ON -D BUILD_WITH_SSL=system -D OPENSSL_VERSION_MAJOR=3  -D BUILD_WITH_PROTOBUF=bundled -D WITH_TEST=ON -D WITH_FAIL_POINT=ON -D WITH_EXAMPLES=ON -D WITH_INSTALL=ON ..
          make -j$(echo "4 * $(nproc)" | bc)
      - name: make unit-test
        run: |
          cd bu
          make -j$(echo "4 * $(nproc)" | bc) unit-test
      - name: Upload LastTest.log
        uses: actions/upload-artifact@v2
        with:
          name: LastTest.log
          path: bu/consensus/unittest/Testing/Temporary/LastTest.log
